name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  ci:
    name: CI (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache Conan packages
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: conan-${{ matrix.os }}-${{ hashFiles('conanfile.py', 'conan.lock') }}
        restore-keys: |
          conan-${{ matrix.os }}-

    - name: Set up Conan
      uses: conan-io/setup-conan@v1

    - name: Detect Conan profile
      run: conan profile detect --force

    - name: Install Conan dependencies
      run: conan install . -s compiler.cppstd=23 -s build_type=Release --lockfile=conan.lock --build=missing

    - name: Run CMake workflow
      run: cmake --workflow --preset ci
