name: Build

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Conan
      uses: conan-io/setup-conan@v1

    - name: Detect Conan profile
      run: make conan-profile

    - name: Check Formatting
      run: make format-check

    - name: Run Clang-Tidy
      run: make lint

  build:
    needs: quality
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [debug, release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Conan
      uses: conan-io/setup-conan@v1

    - name: Detect Conan profile
      run: make conan-profile

    - name: Build And Test (${{ matrix.target }})
      run: make ${{ matrix.target }}
